# fly.toml app configuration file generated for oleg-trello-clone on 2023-08-29T13:41:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oleg-trello-clone"
primary_region = "otp"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
